### ISSUE TITLE
Training sites reduction tool issue (ArcGis pro 2.1.3)

### ISSUE THREAD

**Issue by Eliasmgprado** [gtkfi/ArcSDM#100] opened 2018-06-26 12:03 UTC
Tried to run this tool on ArcGis Pro 2.1.3, but no tools parameters appears. Same occuring in others tools inside Weights of Evidence.

**Comment by Eliasmgprado** [comment] 2018-06-26 12:16
I reinstalled the arcgis pro and now it is working fine. Thanks for the help guys.

**Comment by Eliasmgprado** [comment] 2018-06-26 13:35
Now the parameter had appeared, but when i run the tool, the geoprocessing window stays running for ever and never finish. I'm using the demo data provided for testing. I have tried to run others tools and the same is occurring. 

![image](https://user-images.githubusercontent.com/34711222/41915648-97114cbc-792c-11e8-9867-1991d97e1d7a.png)

**Comment by trotor** [comment] 2018-06-27 05:33
I can't reproduce this error:
![image](https://user-images.githubusercontent.com/10844537/41954587-b38c31d2-79e4-11e8-8765-d558d9fea42f.png)


I believe it could still be faulty or partial installation of ArcGis pro (or missing extension?). Do you have spatial analyst? This tool requires it.

**Comment by Eliasmgprado** [comment] 2018-06-27 11:35
Yes i have the Spatial Analyst license.

![image](https://user-images.githubusercontent.com/34711222/41971442-d1cfac8c-79e4-11e8-8f7b-e735c4627e73.png)

Don't know what is happening, i will keep on tring to run these tools, Thanks for the help.

**Comment by trotor** [comment] 2018-06-27 17:38
Oh, glad that it finally worked out!  I will close this issue for now.

**Closed** 2018-06-28 08:33 UTC
Labels: ArcGis Pro related
