### ISSUE TITLE
Calculate Response not Finding Weights Tables

### ISSUE THREAD

**Issue by reida9** [gtkfi/ArcSDM#75] opened 2017-11-15 22:37 UTC
Hello,

I've been attempting to calculate a response theme for a set of maps and am receiving an error stating that the weights tables cannot be found even though they are in the correct order and in the same GDB. The error output is as follows:

Executing: CalculateResponse 'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Geo_Reclass_Int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Grav_Reclass_int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_K_ReclassProject_Int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Mag_Reclass_Int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Th_ReclassProj_Int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_ThDivKProjec_Reclass_Int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_ThdivU_reClassProj_Int';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_U_Reclass_Int' 'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Geo_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Grav_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_K_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Mag_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Th_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_ThDivK_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_ThdivU_Weights';'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_U_Weights' Carbonatites true -99 1 "D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\W_pprb" "D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\W_std" "D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\W_MDvar" "D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\W_Tstd" "D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\W_conf"
Start Time: Wed Nov 15 14:30:14 2017
Running script CalculateResponse...
Reloaded arcsdm modules

========== arcsdm values  ==========
                     ArcSdm 5.00.22 for ArcGis (Pro and Desktop)

Workspace:           D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb (LocalDatabase)
Scratch workspace:   D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb (LocalDatabase)
Map Units:           meter
Mask:                "Gbboundgeo_Project" and it is FeatureClass
Mask size:           1197816.20989
Cell Size:           1
# Training Sites:    2
Unit Cell Area:      1.0km^2, Cells in area: 1197816.20989 
Prior Probability:   0.000002
Training Set:        D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\Carbonatites
Study Area Raster:   D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\Gbboundgeo_Project
Study Area Area:     1197816.20989km^2

===================== Starting calculate response =====================
Study Area:          1197816.20989
# training points:   2
Prior_prob:          1.66970523816e-06
Input rasters: [u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_Geo_Reclass_Int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_Grav_Reclass_int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_K_ReclassProject_Int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_Mag_Reclass_Int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_Th_ReclassProj_Int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_ThDivKProjec_Reclass_Int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_ThdivU_reClassProj_Int'", u"'D:\\Independent Study\\data files\\Databases\\Prospectivity_Model_Reproject.gdb\\GB_U_Reclass_Int'"]
Input rasters: [u'GB_Geo_Reclass_Int', u'GB_Grav_Reclass_int', u'GB_K_ReclassProject_Int', u'GB_Mag_Reclass_Int', u'GB_Th_ReclassProj_Int', u'GB_ThDivKProjec_Reclass_Int', u'GB_ThdivU_reClassProj_Int', u'GB_U_Reclass_Int']

Creating weight rasters 
=========================================
GP ERRORS:

PYTHON ERRORS:
Traceback Info:
  File "D:\Independent Study\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 133, in Execute
    desc2 = arcpy.Describe(Wts_Table);

Error Info:
    <type 'exceptions.IOError'>: "'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Geo_Weights'" does not exist

Unhandled exception caught
Traceback (most recent call last):
  File "D:\Independent Study\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "D:\Independent Study\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 133, in Execute
    desc2 = arcpy.Describe(Wts_Table);
  File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\__init__.py", line 1253, in Describe
    return gp.describe(value)
  File "c:\program files (x86)\arcgis\desktop10.5\arcpy\arcpy\geoprocessing\_base.py", line 376, in describe
    self._gp.Describe(*gp_fixargs(args, True)))
IOError: "'D:\Independent Study\data files\Databases\Prospectivity_Model_Reproject.gdb\GB_Geo_Weights'" does not exist

Completed script CalculateResponse...
Failed to execute (CalculateResponse).
Failed at Wed Nov 15 14:30:21 2017 (Elapsed Time: 6.58 seconds

Any thoughts?

**Comment by trotor** [comment] 2017-11-16 11:22
I believe this could have something to do with table locks... is the error constant across multiple runs?  - Could you attach screenshot of the tool inputs? I try to reproduce it with our demo data.

**Comment by reida9** [comment] 2017-11-17 03:06
![calc_weights_settings3](https://user-images.githubusercontent.com/33704330/32927407-2c456514-cb01-11e7-8a74-ac8ac326d5a2.jpg)
![calc_weights_settings1](https://user-images.githubusercontent.com/33704330/32927408-2c61f972-cb01-11e7-85c1-1fafa56922f8.jpg)
![calc_weights_settings2](https://user-images.githubusercontent.com/33704330/32927409-2c7a7196-cb01-11e7-92ef-cc8a34b44630.jpg)

**Comment by reida9** [comment] 2017-11-17 03:07
It happens every run as if it cannot find the files

**Comment by trotor** [comment] 2017-11-17 06:35
ACtually this too could have something to do with spaces in directory paths. I will try this ASAP with our test data.

**Comment by reida9** [comment] 2017-11-23 05:55
Just an update, after changing the path names I received the following error:

Executing: CalculateResponse GB_Grav2;GB_Mag D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_Carb2_CD;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Mag_Carb2_CA MntPass true -99 16 D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\W_pprb D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\W_std D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\W_MDvar D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\W_Tstd D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\W_conf
Start Time: Wed Nov 22 21:53:29 2017
Running script CalculateResponse...
Reloaded arcsdm modules

========== arcsdm values  ==========
                     ArcSdm 5.00.25 for ArcGis (Pro and Desktop)

Workspace:           D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb (LocalDatabase)
Scratch workspace:   D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb (LocalDatabase)
Map Units:           meter
Mask:                "Gbboundgeo_Project" and it is FeatureClass
Mask size:           1197816.2099
Cell Size:           4000
# Training Sites:    1
Unit Cell Area:      16.0km^2, Cells in area: 74863.5131187 
Prior Probability:   0.000013
Training Set:        D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\MntPass
Study Area Raster:   D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\Gbboundgeo_Project
Study Area Area:     1197816.2099km^2

===================== Starting calculate response =====================
Study Area:          74863.5131187
# training points:   1
Prior_prob:          1.33576419051e-05
Input rasters: [u'GB_Grav2', u'GB_Mag']
Input rasters: [u'GB_Grav2', u'GB_Mag']

Creating weight rasters 
=========================================
Processing GB_Grav2
 Temp_Raster=D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\temp_raster0
 Wts_Table=D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_Carb2_CD
 Output_Raster: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_W0


Calculate weights caught arcpy.ExecuteError 
Executing: Lookup D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\temp_raster0 WEIGHT D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_W0
Start Time: Wed Nov 22 21:53:44 2017
ERROR 999998: Unexpected Error.
Failed to execute (Lookup).
Failed at Wed Nov 22 21:53:48 2017 (Elapsed Time: 3.52 seconds)
-------------- END EXECUTION ---------------
Unhandled exception caught
Traceback (most recent call last):
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 214, in Execute
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)
ExecuteError: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


Completed script CalculateResponse...
Failed to execute (CalculateResponse).
Failed at Wed Nov 22 21:53:50 2017 (Elapsed Time: 20.58 seconds)
 Hope this helps troubleshoot any issues!

**Comment by trotor** [comment] 2017-11-23 12:09
Thank you for your help on this! I will be very busy for few next weeks but I hope I get someone to reproduce this with our demo dataset.

**Comment by trotor** [comment] 2017-11-23 12:10
(Unexpected error here could have something to do with release table locks or just generic arcmap error which are the worst kind to debug)

**Comment by reida9** [comment] 2017-11-23 20:04
Sure thing! I will dump errors as I receive them in order to help troubleshoot.

Executing: GrandWofe Carb3_MntPass GB_Grav2_reclass_int;GB_K_ReclassProject_Int;GB_Th_ReclassProj_Int;GB_ThDivKProjec_Reclass_Int;GB_ThdivU_reClassProj_Int;GB_U_Reclass_Int;Int_GB_Mag o;o;o;o;o;o;o D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\MntPass true 2 16
Start Time: Thu Nov 23 11:22:25 2017
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.00.25 for ArcGis (Pro and Desktop)

Workspace:           D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb (LocalDatabase)
Scratch workspace:   D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb (LocalDatabase)
Map Units:           meter
Mask:                "Gbboundgeo_Project" and it is FeatureClass
Mask size:           1197816.2099
Cell Size:           MINOF
# Training Sites:    1
Unit Cell Area:      16.0km^2, Cells in area: 74863.5131187 
Prior Probability:   0.000013
Training Set:        D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\MntPass
Study Area Raster:   D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\Gbboundgeo_Project
Study Area Area:     1197816.2099km^2
========== Starting GrandWofe ====================
Calculating weights for GB_Grav2_reclass_int (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_reclass_int_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_reclass_int_Carb3_MntPass_CD

Calculating weights for GB_K_ReclassProject_Int (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_K_ReclassProject_Int_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_K_ReclassProject_Int_Carb3_MntPass_CD

Calculating weights for GB_Th_ReclassProj_Int (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Th_ReclassProj_Int_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Th_ReclassProj_Int_Carb3_MntPass_CD

Calculating weights for GB_ThDivKProjec_Reclass_Int (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_ThDivKProjec_Reclass_Int_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_ThDivKProjec_Reclass_Int_Carb3_MntPass_CD

Calculating weights for GB_ThdivU_reClassProj_Int (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_ThdivU_reClassProj_Int_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_ThdivU_reClassProj_Int_Carb3_MntPass_CD

Calculating weights for GB_U_Reclass_Int (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_U_Reclass_Int_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_U_Reclass_Int_Carb3_MntPass_CD

Calculating weights for Int_GB_Mag (o)...
     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\Int_GB_Mag_Carb3_MntPass_CA

     ...done
Result: D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\Int_GB_Mag_Carb3_MntPass_CD

------ Running tests... (0) ------
A: Response & Logistic Regression: GB_Grav2_reclass_int;GB_K_ReclassProject_Int;GB_Th_ReclassProj_Int;GB_ThDivKProjec_Reclass_Int;GB_ThdivU_reClassProj_Int;GB_U_Reclass_Int;Int_GB_Mag,D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_reclass_int_Carb3_MntPass_CA;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_K_ReclassProject_Int_Carb3_MntPass_CA;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Th_ReclassProj_Int_Carb3_MntPass_CA;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_ThDivKProjec_Reclass_Int_Carb3_MntPass_CA;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_ThdivU_reClassProj_Int_Carb3_MntPass_CA;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_U_Reclass_Int_Carb3_MntPass_CA;D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\Int_GB_Mag_Carb3_MntPass_CA

 Calculating response... 
GP ERRORS:


Executing: Lookup D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\temp_raster1 WEIGHT D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_r_W2
Start Time: Thu Nov 23 11:59:41 2017
ERROR 999998: Unexpected Error.
Failed to execute (Lookup).
Failed at Thu Nov 23 11:59:44 2017 (Elapsed Time: 3.13 seconds)
Unhandled exception caught
Traceback (most recent call last):
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 214, in Execute
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)
ExecuteError: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


Failed to execute (CalculateResponse).


PYTHON ERRORS:
Traceback Info:
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\grand_wofe_lr.py", line 189, in execute
    Output_MD_Variance_Raster, Output_Total_Std_Dev_Raster, Output_Confidence_Raster)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: 

Executing: Lookup D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\temp_raster1 WEIGHT D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_r_W2
Start Time: Thu Nov 23 11:59:41 2017
ERROR 999998: Unexpected Error.
Failed to execute (Lookup).
Failed at Thu Nov 23 11:59:44 2017 (Elapsed Time: 3.13 seconds)
Unhandled exception caught
Traceback (most recent call last):
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 214, in Execute
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)
ExecuteError: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


Failed to execute (CalculateResponse).



Traceback (most recent call last):
  File "<string>", line 149, in execute
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\grand_wofe_lr.py", line 189, in execute
    Output_MD_Variance_Raster, Output_Total_Std_Dev_Raster, Output_Confidence_Raster)
  File "D:\Independent_Study\ArcSDM-master\Toolbox\ArcSDM.pyt", line 508, in CalculateResponse
    def updateMessages(self, parameters):
ExecuteError: 

Executing: Lookup D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\temp_raster1 WEIGHT D:\Independent_Study\data_files\Databases\Mnt_PassModel.gdb\GB_Grav2_r_W2
Start Time: Thu Nov 23 11:59:41 2017
ERROR 999998: Unexpected Error.
Failed to execute (Lookup).
Failed at Thu Nov 23 11:59:44 2017 (Elapsed Time: 3.13 seconds)
Unhandled exception caught
Traceback (most recent call last):
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "D:\Independent_Study\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 214, in Execute
    gp.Lookup_sa(Temp_Raster,"WEIGHT",Output_Raster)
ExecuteError: ERROR 999998: Unexpected Error.
Failed to execute (Lookup).


Failed to execute (CalculateResponse).


Failed to execute (GrandWofe).
Failed at Thu Nov 23 12:00:01 2017 (Elapsed Time: 37 minutes 35 seconds)

**Comment by trotor** [comment] 2017-12-22 15:35
Some fixes on Grand Wofe made, probably not working yet but worth trying. Seems to be somekind of locking problem and VERY difficult to track

**Comment by tachyon-work** [comment] 2018-04-24 07:12
I will almost guarantee the failure is because you have only one single training point. None of your weights tables will be statistically valid with only 1 training point. If the none of the weights tables have statistically valid results, calculate response will always fail.

**Comment by trotor** [comment] 2018-04-26 12:54
To get back on this one - from the error message I assume this was ran on Arcgis pro and there seems to be big problems currently.

**Comment by trotor** [comment] 2018-04-26 12:55
New version of sdmvalues.py contains arcgis environment info so it is easier for devs to see what was ran and on which version.

**Comment by artolaiho** [comment] 2020-06-16 07:05
Seems that it is input data problem so I am closing this issue.

**Closed by artolaiho** 2020-06-16 07:05 UTC
Labels: Waiting input, bug, help wanted
